services:
  - type: web
    name: linebot-qroq3
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app_fastapi:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CHANNEL_ACCESS_TOKEN
        sync: false
      - key: CHANNEL_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: BASE_URL
        sync: false
    autoDeploy: true
    plan: free